[project]
name = "incident-management-ai-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "langchain",
    "langgraph",
    "psycopg2-binary",
]

[dependency-groups]
dev = [
    "pytest",
]

[project.optional-dependencies]
evaluation = [
    "deepeval",
    "mlflow",
    "ragas",
]

[tool.uv]
package = false
